### ISSUE TITLE
optional fields

### ISSUE THREAD

**Issue by serbaut** [pomack/thrift4go#1]
There seems to be no support for optional string fields for write methods. Maybe you need to use *string and check for nil in those cases. Or always use *string and skip nil as the python driver does.

**Comment by pomack** [comment]
Go itself doesn't support strings, integers, or floats as being nil.  There is a default value for all types in Go.  When I created the thrift4go, I made an assumption that people would NOT want every field to be a pointer to a value just due to optionality.  The default value for a string is the empty string, the default value for integer is 0 and default value for float is 0.0.  To support full optionality as you describe would require a pointer for every field, which would not be performant.

**Comment by pomack** [comment]
After thinking about it, this is probably a better response.

How do you define your structs in a given language?

In Go, people will normally do something like:

struct {
  Field1 bool
  Field2 int
  Field3 string
  Field4 []int
  Field5 map[string]int
}

Python supports the idea that any field can be None, since it doesn't enforce types.  Java assumes the base types cannot be null, but anything based off of Object (including String), can be null.  Go assumes the base types cannot be nil, but that anything else can be nil.  The main difference between Go and Java is that string is considered a base type in Go whereas it is not in Java.

Since people would rather specify their objects as having fields of type string rather than *string in Go or []string, I have to go with the assumption that in Go, we'd treat an optional string as a string that hasn't been assigned to.  In Java this is null, in Go it is the empty string.  Same thing for int, float, and boolean.  I assume an optional field (unless a default value is specified) will default to the local value of the language.  If a default value is specified, then the default value will be applied when optional fields are not specified.

To me, you should always have default values if you're going to have optional fields and expect a particular value.

Does this make sense?  Do you agree or disagree?

**Comment by serbaut** [comment]
I dont know enough about thrift or go to have a strong opinion about it. I ran into the issue when playing around with a go client for cassandra. The server rejected a request when i passed "" (uninitialized string) instead of not passing anything (for super_column).

```
struct ColumnPath {
    3: required string column_family,
    4: optional binary super_column,
    5: optional binary column,
}
```

**Comment by serbaut** [comment]
Some options:
1. define "" to be the same as undefined
2. use *string
3. make up some magic string for undefined "--nil--" (ugh)
4. include a []null_mask or map in the types that you have to manipulate
5. include helper fields like "foo.super_column_is_nil = true"

I dont think option 1 will work, especially not for int and float. I dont like 3. 4 not so much either. 5 maybe.

Afaict the best option is to change the fields to pointers.

**Comment by serbaut** [comment]
Acually the c++ driver defines a sub struct that contains isset fields for all optional fields so that is clearly the way to go.

```
typedef struct _ColumnPath__isset {
  _ColumnPath__isset() : super_column(false), column(false) {}
  bool super_column;
  bool column;
} _ColumnPath__isset;

class ColumnPath {
  std::string column_family;
  std::string super_column;
  std::string column;

  _ColumnPath__isset __isset;
}
```

edit: not sure if it is possible to reproduce the c++ magic of setting the isset fields automatically in go.
edit2: apparently there is no magic. i just assumed. it provides setters methods.

**Comment by pomack** [comment]
OK, now I'm confused.  The string field column_family is required.  The
optional fields are binary, which I believe I implemented as []byte, but
would have to check the source to confirm.  A []byte should support optional
as nil.

Am I missing something?
On Jul 14, 2011 6:33 PM, "serbaut" <
reply@reply.github.com>
wrote:

**Comment by serbaut** [comment]
binary seems to be a non utf-8 string in thrift http://wiki.apache.org/thrift/ThriftTypes mapped to string in both go and c++

**Comment by pomack** [comment]
hmmm, looking at the C++ thrift compiler, it appears they made binary a subtype of string.  But I based my code on the Python compiler which makes very few references to binary.  This will require some time.

**Comment by kungfuelmosan** [comment]
Hey Pomack, Any news on this? I too am looking to connect to cassandra from Go :) Cheers!

**Comment by pomack** [comment]
The summer has kept me busy and I haven't had a chance to look at this.  I'll try to have something working by the end of September for binary, but getting the isset stuff working will require a lot more time due to the amount of code generation I will need to add to the compiler.

**Comment by pomack** [comment]
I've pushed out updated code to support both optional and binary fields, however I haven't tested it beyond checking that it compiles and generated compilable code.  The optional field support assumes that if a number is the default value (or 0 if no default value is provided), then it is not set, otherwise it is set.  If a string, map, list, set, or binary is empty then it isn't set.  

There were two files that were modified for this purpose:
compiler/cpp/src/generate/t_go_generator.cc
lib/go/thrift/ttype.go

Can someone please update these two files in their checkouts, build thrift, generate the Cassandra libraries, and let me know how it works?

**Comment by pomack** [comment]
Anyone interested in trying this out?  I don't have a Cassandra instance up and running to test whether or not this works.  If you wait till I test it, it'll be the end of September.

**Comment by reds** [comment]
Hi, thanks for your great work. I'v had success with cassandra add,insert, get and get_slice. I did have to make a very minor change in t_go_generator.cc, get_slice was giving back twice as many rows as it should have. Optional fields work great now.

```
diff --git a/compiler/cpp/src/generate/t_go_generator.cc b/compiler/cpp/src/generate/t_go_generator.cc
index 26569fa..26e8e86 100755
--- a/compiler/cpp/src/generate/t_go_generator.cc
+++ b/compiler/cpp/src/generate/t_go_generator.cc
@@ -703,8 +703,9 @@ string t_go_generator::render_const_value(t_type* type, t_const_value* value, co
   } else if (type->is_list()) {
     t_type* etype = ((t_list*)type)->get_elem_type();                                                                                                       
     const vector<t_const_value*>& val = value->get_list();                                                                                                  
+    out << "// generating list" << endl;                                                                                                                    
     out <<
-      "thrift.NewTList(" << type_to_enum(etype) << ", " << val.size() << ")" << endl <<
+      "thrift.NewTList(" << type_to_enum(etype) << ", " << "0" << ")" << endl <<
       indent() << "{" << endl;                                                                                                                              
     indent_up();                                                                                                                                            
     vector<t_const_value*>::const_iterator v_iter;                                                                                                          
@@ -2471,7 +2472,7 @@ void t_go_generator::generate_deserialize_container(ofstream &out,
                            escape_string(prefix) << "\", \"\", " <<
                            err << ")" << endl <<
       indent() << "}" << endl <<
-      indent() << prefix << eq << "thrift.NewTList(" << etype << ", " << size << ")" << endl;                                                               
+      indent() << prefix << eq << "thrift.NewTList(" << etype << ", " << "0" << ")" << endl;                                                                
   } else {
     throw "INVALID TYPE IN generate_deserialize_container '" + ttype->get_name() + "' for prefix '" + prefix + "'";                                         
   }
```

**Comment by pomack** [comment]
The real problem is line 51 of tlist.go...it should only reserve
capacity...not resize...or I should change how elements are added/stored in
the tlist.  I'll push out a patch next week when I get back to the office.

Thanks for letting me know it works with Cassandra!

Once I get the patch out, can you test it again so I can ask the changes to
be included in the official distribution?

## 

Aalok Shah
aalok@shah.ws
On Dec 30, 2011 2:08 PM, "Martin Redmond" <
reply@reply.github.com>
wrote:

**Comment by reds** [comment]
I'll test again whenever you need it. I'll be working on batch_mutate next.

**Comment by araddon** [comment]
Reds, if you see this issue on batch mutate (I did), there is another issue with optional fields that comes up on multi-columns.  

https://github.com/araddon/thrift/commit/801e7688bc06da48c2625f639499960f347e6dbc

**Comment by pomack** [comment]
Hey Martin,

I've pushed out the one-line change to tlist.go that should fix the TList double-sizing issue.
Some of the other changes to the release and go.r60 label are mostly innocuous except for changing TType from an int to an interface to better support the string vs. binary issues.

The code generator for Go hasn't been updated since December 9th, so please revert your changes to t_go_generator.cc when testing.

Let me know whether it works for you.

**Comment by reds** [comment]
Aalok, everything I tested last week; add insert,get and get_slice work with your latest commit. Will get back to you re batch_commit.

**Comment by pomack** [comment]
Sweet!  Thanks Martin.

**Comment by pomack** [comment]
Hey Martin, have you been able to test out batch_commit?

**Comment by reds** [comment]
I just tried and came up with the following problems: https://gist.github.com/1817853 and https://gist.github.com/1817869. 

Thanks.

**Comment by pomack** [comment]
For the first one, can you change the two panic statements around like 376 in tmap.go to be:
    panic("Should never be here, type: " + p.KeyType().String())
I'd like to know what type they are.  If it is a STRUCT/SET/LIST/MAP, then it should've been handled in tmap.go then it should've been handled in lines 310 - 324 before it ever got into the switch statement that is causing the problem.  If it is different, I definitely need to know the type.

The second one is based on generated code. I'm assuming it's trying to write a binary blob but is calling WriteString.  Can you send a gist with the .thrift file and another with the generated code so I can see what it's trying to do and why the value type-casting is wrong?

**Comment by reds** [comment]
The binary case gives:

```
=== RUN  cassandraSimple.TestBatchBinary
panic: Should never be here type: BINARY
```

I just tried STRING to see what would happen, does it need to be supported?

**Comment by pomack** [comment]
I've just pushed out an update to the master, release, and weekly branches to better support BINARY in tmap, tlist, and tset as elements.

Try it out, I believe this should fix it (although it is untested).

**Comment by pomack** [comment]
Hey Martin, did the fix work?

**Comment by reds** [comment]
Yes.  It works for some simple tests: multi row insertion and updates.  I haven't tried deletion yet (I ttl all my data) but I'm sure it will not be a problem.

Thanks again for your  cool work.
